/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    './index.html',
    './src/**/*.{js,jsx}',
  ],
  theme: {
    extend: {
      colors: {
        background: '#0b1326',
        'surface-dim': '#0b1326',
        surface: '#0b1326',
        'surface-bright': '#31394d',
        'surface-container-lowest': '#060e20',
        'surface-container-low': '#131b2e',
        'surface-container': '#171f33',
        'surface-container-high': '#222a3d',
        'surface-container-highest': '#2d3449',
        'on-surface': '#dae2fd',
        'on-surface-variant': '#bcc9cd',
        'inverse-surface': '#dae2fd',
        'inverse-on-surface': '#283044',
        outline: '#869397',
        'outline-variant': '#3d494c',
        'surface-tint': '#4cd7f6',
        primary: '#4cd7f6',
        'on-primary': '#003640',
        'primary-container': '#06b6d4',
        'on-primary-container': '#00424f',
        'inverse-primary': '#00687a',
        secondary: '#bcc7de',
        'on-secondary': '#263143',
        'secondary-container': '#3e495d',
        'on-secondary-container': '#aeb9d0',
        tertiary: '#ffb873',
        'on-tertiary': '#4b2800',
        'tertiary-container': '#e89337',
        'on-tertiary-container': '#5b3200',
        error: '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
        'primary-fixed': '#acedff',
        'primary-fixed-dim': '#4cd7f6',
        'on-primary-fixed': '#001f26',
        'on-primary-fixed-variant': '#004e5c',
        'secondary-fixed': '#d8e3fb',
        'secondary-fixed-dim': '#bcc7de',
        'on-secondary-fixed': '#111c2d',
        'on-secondary-fixed-variant': '#3c475a',
        'tertiary-fixed': '#ffdcbf',
        'tertiary-fixed-dim': '#ffb873',
        'on-tertiary-fixed': '#2d1600',
        'on-tertiary-fixed-variant': '#6a3b00',
        'surface-variant': '#2d3449',
        'on-background': '#dae2fd',
      },
      fontFamily: {
        'headline-lg': ['"Hanken Grotesk"', 'sans-serif'],
        'headline-md': ['"Hanken Grotesk"', 'sans-serif'],
        'headline-sm': ['"Hanken Grotesk"', 'sans-serif'],
        'body-lg': ['"Hanken Grotesk"', 'sans-serif'],
        'body-md': ['"Hanken Grotesk"', 'sans-serif'],
        'data-mono': ['"JetBrains Mono"', 'monospace'],
        'label-caps': ['"JetBrains Mono"', 'monospace'],
      },
      fontSize: {
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'data-mono': ['14px', { lineHeight: '20px', fontWeight: '500' }],
        'label-caps': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '700' }],
      },
      borderRadius: {
        sm: '0.25rem',
        DEFAULT: '0.5rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
        full: '9999px',
      },
      spacing: {
        base: '4px',
        xs: '4px',
        sm: '8px',
        md: '16px',
        lg: '24px',
        xl: '40px',
        'container-margin': '24px',
        gutter: '16px',
      },
    },
  },
  plugins: [],
};
