import { useState } from 'react';
import { downloadCsv } from '../utils/nodeRedApi';

/**
 * Reports & Documentation screen — route: /reports
 *
 * Report generator cards + export history. Export history requires the
 * Node-RED HTTP endpoint to be configured and serving data.
 *
 * @param {{ mqtt: object }} props
 */
export default function Reports({ mqtt }) {
  const { connectionState } = mqtt;
  const isLive = connectionState === 'connected';
  const [generating, setGenerating] = useState(null);

  function handleGenerate(reportName) {
    setGenerating(reportName);
    setTimeout(() => setGenerating(null), 4500);
  }

  async function handleExportCsv() {
    try {
      await downloadCsv('weights');
    } catch {
      console.warn('CSV export failed — Node-RED may be offline.');
    }
  }

  return (
    <div className="flex flex-col min-h-full">
      {/* Page Header */}
      <section className="mb-xl flex justify-between items-end">
        <div>
          <h2 className="font-headline-lg text-headline-lg text-on-surface">
            Reports &amp; Documentation
          </h2>
          <p className="font-body-lg text-body-lg text-on-surface-variant max-w-2xl">
            Standardized operational reporting for export-grade compliance and
            facility throughput monitoring.
          </p>
        </div>
        <div className="flex items-center gap-sm">
          <div className="flex items-center gap-xs px-sm py-1 bg-primary/10 border border-primary/20 rounded">
            <span className={`w-2 h-2 rounded-full ${isLive ? 'bg-primary animate-pulse' : 'bg-[#EF4444]'}`} />
            <span className="font-label-caps text-[10px] text-primary">
              {isLive ? 'System Online' : 'MQTT Offline'}
            </span>
          </div>
        </div>
      </section>

      {/* Report Generator Cards (3 cards) */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-lg">
        {/* Card 1: Daily Audit Summary */}
        <ReportCard
          icon="description"
          badge="PDF ONLY"
          badgeClass="text-on-surface-variant bg-surface-container-high"
          title="Daily Audit Summary"
          description="Complete daily grading audit with batch traceability and QA sign-off."
          generating={generating}
          onGenerate={() => handleGenerate('Daily Audit Summary')}
          onExportCsv={handleExportCsv}
        />

        {/* Card 2: Grade Quality Export */}
        <ReportCard
          icon="verified"
          badge="MOST USED"
          badgeClass="text-primary bg-primary/10 border border-primary/20"
          title="Grade Quality Export"
          description="Export grade distribution data with statistical process control metrics."
          decorative
          generating={generating}
          onGenerate={() => handleGenerate('Grade Quality Export')}
          onExportCsv={handleExportCsv}
        />

        {/* Card 3: Device Downtime Log */}
        <ReportCard
          icon="warning"
          badge="MAINTENANCE"
          badgeClass="text-tertiary bg-tertiary/10 border border-tertiary/20"
          title="Device Downtime Log"
          description="Scheduled and unscheduled downtime tracking with MTBF calculations."
          generating={generating}
          onGenerate={() => handleGenerate('Device Downtime Log')}
          onExportCsv={handleExportCsv}
          selectDateRange
        />
      </div>

      {/* Recent Export History */}
      <section className="mt-xl">
        <h3 className="font-label-caps text-label-caps text-on-surface-variant mb-md tracking-widest">
          RECENT EXPORT HISTORY
        </h3>
        <div className="bg-surface-container border border-outline-variant rounded overflow-hidden">
          <table className="w-full text-left">
            <thead className="bg-surface-container-high border-b border-outline-variant">
              <tr>
                <th className="px-md py-sm font-label-caps text-label-caps text-on-surface-variant">File Name</th>
                <th className="px-md py-sm font-label-caps text-label-caps text-on-surface-variant">Generated By</th>
                <th className="px-md py-sm font-label-caps text-label-caps text-on-surface-variant">Date</th>
                <th className="px-md py-sm font-label-caps text-label-caps text-on-surface-variant text-right">Download</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td colSpan="4" className="px-md py-xl text-center">
                  <div className="flex flex-col items-center gap-sm">
                    <span className="material-symbols-outlined text-3xl text-on-surface-variant/20">
                      folder_off
                    </span>
                    <p className="font-body-md text-body-md text-on-surface-variant">
                      No exports yet. Generate a report above to see it here.
                    </p>
                    <p className="font-data-mono text-[10px] text-on-surface-variant/50">
                      Requires Node-RED at {import.meta.env.VITE_NODE_RED_BASE_URL || 'http://localhost:1880'}
                    </p>
                  </div>
                </td>
              </tr>
            </tbody>
          </table>
          <div className="p-md flex justify-center border-t border-outline-variant">
            <button className="font-label-caps text-[10px] text-on-surface-variant hover:text-primary transition-colors">
              VIEW FULL AUDIT LOG
            </button>
          </div>
        </div>
      </section>

      {/* Footer Status Strip */}
      <footer className="mt-lg bg-surface-container-low border border-outline-variant p-md rounded flex justify-between items-center">
        <div className="flex items-center gap-xl">
          <div className="flex items-center gap-xs">
            <span className={`w-1.5 h-1.5 rounded-full ${isLive ? 'bg-[#10B981]' : 'bg-[#EF4444]'}`} />
            <span className="font-data-mono text-[10px] text-on-surface-variant">
              {isLive ? 'MQTT: Connected' : 'MQTT: Offline'}
            </span>
          </div>
        </div>
        <div className="flex items-center gap-md">
          <span className="font-data-mono text-[10px] text-on-surface-variant">
            © 2024 Bukidnon Fresh Pineapple Corp. • Node ID: BFPC-04-B
          </span>
        </div>
      </footer>
    </div>
  );
}

/** Reusable report generator card. */
function ReportCard({
  icon, badge, badgeClass, title, description, decorative,
  generating, onGenerate, onExportCsv, selectDateRange,
}) {
  const isThisGenerating = generating === title;

  return (
    <article className={`bg-surface-container border border-outline-variant rounded p-lg flex flex-col justify-between group hover:border-primary/50 transition-all duration-300 ${decorative ? 'relative overflow-hidden' : ''}`}>
      {decorative && (
        <div className="absolute top-0 right-0 p-lg opacity-10 group-hover:opacity-20 transition-opacity">
          <span className="material-symbols-outlined leading-none" style={{ fontSize: '160px' }}>verified</span>
        </div>
      )}
      <div className="relative z-10">
        <div className="flex justify-between items-start mb-md">
          <div className="p-sm bg-surface-variant rounded">
            <span className="material-symbols-outlined text-primary">{icon}</span>
          </div>
          <span className={`font-label-caps text-[10px] px-sm py-0.5 rounded ${badgeClass}`}>{badge}</span>
        </div>
        <h3 className="font-headline-sm text-headline-sm text-on-surface mb-sm">{title}</h3>
        <p className="font-body-md text-body-md text-on-surface-variant mb-xl leading-relaxed">{description}</p>
      </div>
      <div className="space-y-md relative z-10">
        <div>
          <label className="font-label-caps text-[10px] text-on-surface-variant block mb-xs">DATE RANGE</label>
          {selectDateRange ? (
            <div className="flex items-center gap-sm bg-surface-container-high border border-outline-variant rounded px-sm py-xs h-10">
              <span className="material-symbols-outlined text-xs text-on-surface-variant">history</span>
              <select className="bg-transparent border-none p-0 text-on-surface font-data-mono text-sm focus:ring-0 w-full appearance-none">
                <option>Last 7 Days</option>
                <option>Last 30 Days</option>
                <option>Current Shift</option>
                <option>Custom Range</option>
              </select>
            </div>
          ) : (
            <div className="flex items-center gap-sm bg-surface-container-high border border-outline-variant rounded px-sm py-xs h-10">
              <span className="material-symbols-outlined text-xs text-on-surface-variant">calendar_today</span>
              <input className="bg-transparent border-none p-0 text-on-surface font-data-mono text-sm focus:ring-0 w-full" type="date" defaultValue="2024-05-24" />
            </div>
          )}
        </div>
        <div className="flex flex-col gap-sm">
          <button
            onClick={onGenerate}
            disabled={generating !== null}
            className={`w-full font-label-caps py-sm flex items-center justify-center gap-sm rounded transition-all ${
              isThisGenerating ? 'bg-[#10B981] text-white' : 'bg-primary text-on-primary hover:brightness-110'
            }`}
          >
            <span className="material-symbols-outlined text-sm">
              {isThisGenerating ? 'sync' : 'article'}
            </span>
            {isThisGenerating ? 'PROCESSING...' : 'Generate Report'}
          </button>
          <button onClick={onExportCsv} className="w-full border border-outline-variant text-on-surface font-label-caps py-sm rounded hover:bg-surface-variant transition-all">
            Export CSV
          </button>
        </div>
      </div>
    </article>
  );
}
