import { Router } from 'express';
import { ocrQuery, query } from '../db.js';
import { authenticate } from '../middleware/auth.js';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import XLSX from 'xlsx';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const REPORTS_DIR = path.resolve(__dirname, '..', '..', '..', 'reports');
const STATION = 'Scale 04 — Grading Station';

if (!fs.existsSync(REPORTS_DIR)) {
  fs.mkdirSync(REPORTS_DIR, { recursive: true });
}

const router = Router();
router.use(authenticate);

// ── formatters ────────────────────────────────────────────────────────

const fmtTs = ts => {
  // Trim microsecond precision: "2026-08-07 04:41:05.374725" → "2026-08-07 04:41:05"
  if (!ts) return '';
  return String(ts).replace(/\.\d+/, '').replace('T', ' ');
};

const fmtGrade = g => String(g || '').charAt(0).toUpperCase() + String(g || '').slice(1);
const fmtStatus = s => String(s || '').charAt(0).toUpperCase() + String(s || '').slice(1);
const fmtWeight = w => (w != null ? `${Number(w).toFixed(2)} g` : '');

// Audit status color mapping (matches Reports UI convention)
const STATUS_COLORS = {
  pending:   '#F59E0B',  // amber
  confirmed: '#10B981',  // green
  flagged:   '#EF4444',  // red
  approved:  '#10B981',
  rejected:  '#EF4444',
};

function statusColor(status) {
  return STATUS_COLORS[(status || 'pending').toLowerCase()] || '#94A3B8';
}

// ── document header ───────────────────────────────────────────────────

function docHeader({ title, date, days, generatedBy }) {
  const now = new Date().toISOString().slice(0, 19).replace('T', ' ');
  const range = days ? `${date} (${days}-day window)` : date;
  return {
    heading: 'Report Information',
    text: [
      `Station: ${STATION}`,
      `Date Range: ${range}`,
      `Generated By: ${generatedBy}`,
      `Generated At: ${now}`,
    ].join('  |  '),
  };
}

// ── HTML report builder ───────────────────────────────────────────────

function buildHtmlReport(title, sections) {
  const rows = sections.map(s => {
    if (s.table) {
      const alignMap = s.align || [];
      const headers = s.table[0].map((h, i) => {
        const al = alignMap[i] || 'left';
        return `<th style="text-align:${al}">${h}</th>`;
      }).join('');
      const bodyRows = s.table.slice(1).map(row =>
        `<tr>${row.map((c, i) => {
          const al = alignMap[i] || 'left';
          // Color-code audit status cells
          let style = `text-align:${al}`;
          if (s.statusCol !== undefined && i === s.statusCol) {
            const color = statusColor(c);
            style += `;color:${color};font-weight:600`;
          }
          return `<td style="${style}">${c}</td>`;
        }).join('')}</tr>`
      ).join('');
      return `<h3>${s.heading}</h3><table border="1" cellpadding="6" style="border-collapse:collapse;width:100%;font-size:13px"><thead><tr>${headers}</tr></thead><tbody>${bodyRows}</tbody></table>`;
    }
    return `<h3>${s.heading}</h3><p style="color:#64748b">${s.text}</p>`;
  }).join('');

  return `<!DOCTYPE html><html><head><meta charset="utf-8"><title>${title}</title>
<style>
body{font-family:'Segoe UI',Arial,sans-serif;max-width:960px;margin:32px auto;color:#1e293b;background:#fff}
h1{color:#0f766e;border-bottom:2px solid #0f766e;padding-bottom:8px;font-size:22px}
h2{color:#334155;font-size:16px;margin-top:24px}
h3{color:#475569;font-size:13px;margin:16px 0 6px;text-transform:uppercase;letter-spacing:.5px}
table{margin:8px 0 20px}th{background:#f1f5f9;font-weight:600;font-size:12px}td,th{padding:7px 10px}
.footer{margin-top:32px;border-top:1px solid #e2e8f0;padding-top:12px;font-size:11px;color:#94a3b8}
.header-info{background:#f8fafc;border:1px solid #e2e8f0;border-radius:6px;padding:12px 16px;font-size:12px;color:#475569}
</style></head>
<body><h1>${title}</h1>${rows}
<div class="footer">&copy; ${new Date().getFullYear()} Bukidnon Fresh Pineapple Corp. &bull; Pineapple Hub &bull; ${STATION}</div>
</body></html>`;
}

// ── CSV builder (clean, parseable, no decoration) ─────────────────────

function buildCsv(headers, rows) {
  const escape = v => `"${String(v).replace(/"/g, '""')}"`;
  return [headers.map(escape).join(','), ...rows.map(r => r.map(escape).join(','))].join('\n');
}

// ── XLSX builder (styled: column widths, alignment, color-coded status) ─

function buildXlsx(sheets) {
  const wb = XLSX.utils.book_new();
  for (const { name, headers, rows, align, statusCol } of sheets) {
    const ws = XLSX.utils.aoa_to_sheet([headers, ...rows]);

    // Column widths
    const colWidths = headers.map((h, i) => {
      const maxLen = Math.max(h.length, ...rows.map(r => String(r[i] || '').length));
      return { wch: Math.min(Math.max(maxLen + 3, 10), 30) };
    });
    ws['!cols'] = colWidths;

    // Apply alignment per column
    const range = XLSX.utils.decode_range(ws['!ref'] || 'A1');
    for (let R = range.s.r; R <= range.e.r; R++) {
      for (let C = range.s.c; C <= range.e.c; C++) {
        const addr = XLSX.utils.encode_cell({ r: R, c: C });
        if (!ws[addr]) continue;
        const cell = ws[addr];
        const colAlign = align ? align[C] : 'left';
        cell.s = cell.s || {};

        // Header row: bold
        if (R === 0) {
          cell.s.font = { bold: true };
        }

        // Alignment
        if (colAlign === 'right') cell.s.alignment = { horizontal: 'right' };
        else if (colAlign === 'center') cell.s.alignment = { horizontal: 'center' };
        else cell.s.alignment = { horizontal: 'left' };

        // Color-code audit status
        if (statusCol !== undefined && C === statusCol && R > 0) {
          const val = String(cell.v || '');
          const color = statusColor(val);
          // Convert hex to ARGB for xlsx
          const rgb = color.replace('#', '');
          cell.s.font = { ...cell.s.font, color: { rgb: `FF${rgb}` }, bold: true };
        }

        // Bold Batch ID column
        if (C === 0 && R > 0) {
          cell.s.font = { ...cell.s.font, bold: true };
        }
      }
    }

    XLSX.utils.book_append_sheet(wb, ws, name);
  }
  return XLSX.write(wb, { type: 'buffer', bookType: 'xlsx' });
}

// ── save & respond ────────────────────────────────────────────────────

async function saveAndRespond(res, reportType, format, fileName, content, buffer, generatedBy) {
  const ext = format === 'xlsx' ? 'xlsx' : format === 'csv' ? 'csv' : 'html';
  const baseName = `${fileName}-${Date.now()}.${ext}`;
  const filePath = path.join(REPORTS_DIR, baseName);

  if (buffer) {
    fs.writeFileSync(filePath, buffer);
  } else {
    fs.writeFileSync(filePath, content, 'utf-8');
  }

  const { rows } = await query(
    `INSERT INTO grading.report_exports (file_name, report_type, format, generated_by, file_path)
     VALUES ($1, $2, $3, $4, $5) RETURNING id`,
    [baseName, reportType, format, generatedBy || 'Admin User', filePath]
  );

  const mime = format === 'xlsx' ? 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
    : format === 'csv' ? 'text/csv' : 'text/html';
  const data = buffer || Buffer.from(content, 'utf-8');
  res.setHeader('Content-Type', mime);
  res.setHeader('Content-Disposition', `attachment; filename="${baseName}"`);
  res.setHeader('X-Export-Id', rows[0].id);
  res.send(data);
}

// ═══════════════════════════════════════════════════════════════════════
// POST /api/reports/daily-audit
// ═══════════════════════════════════════════════════════════════════════

router.post('/daily-audit', async (req, res) => {
  try {
    const { date, format = 'html' } = req.body;
    const generatedBy = req.user?.email || 'Admin User';

    // OCR text/confidence intentionally excluded — they are internal pipeline debug fields
    const { rows } = await ocrQuery(
      `SELECT batch_id, grade, weight_g, audit_status, timestamp::text
       FROM operations_log
       WHERE DATE(timestamp) = $1
       ORDER BY timestamp ASC`,
      [date]
    );

    const headers = ['Batch ID', 'Grade', 'Weight', 'Audit Status', 'Timestamp'];
    const align   = ['left',   'center', 'right',  'center',        'left'];
    const dataRows = rows.map(r => [
      r.batch_id,
      fmtGrade(r.grade),
      fmtWeight(r.weight_g),
      fmtStatus(r.audit_status),
      fmtTs(r.timestamp),
    ]);

    const hdr = docHeader({ title: 'Daily Audit Summary', date, generatedBy });

    if (format === 'csv') {
      const csv = buildCsv(headers, dataRows);
      return saveAndRespond(res, 'daily-audit', 'csv', `audit-${date}`, csv, null, generatedBy);
    }

    if (format === 'xlsx') {
      const buf = buildXlsx([{ name: 'Daily Audit', headers, rows: dataRows, align, statusCol: 3 }]);
      return saveAndRespond(res, 'daily-audit', 'xlsx', `audit-${date}`, null, buf, generatedBy);
    }

    // HTML
    const html = buildHtmlReport(`Daily Audit Summary — ${date}`, [
      hdr,
      { heading: 'Summary', text: `Total Entries: ${rows.length}` },
      { heading: 'Audit Records', table: [headers, ...dataRows], align, statusCol: 3 },
    ]);
    saveAndRespond(res, 'daily-audit', 'html', `audit-${date}`, html, null, generatedBy);
  } catch (err) {
    console.error('[Reports] daily-audit error:', err);
    res.status(500).json({ error: 'Report generation failed' });
  }
});

// ═══════════════════════════════════════════════════════════════════════
// POST /api/reports/grade-quality
// ═══════════════════════════════════════════════════════════════════════

router.post('/grade-quality', async (req, res) => {
  try {
    const { date, format = 'html', days = 7 } = req.body;
    const generatedBy = req.user?.email || 'Admin User';

    const { rows: dist } = await ocrQuery(
      `SELECT grade, COUNT(*)::int AS count,
         ROUND(COUNT(*) * 100.0 / SUM(COUNT(*)) OVER (), 1) AS percentage
       FROM operations_log
       WHERE timestamp >= ($1::date - ($2 || ' days')::interval) AND timestamp <= ($1::date + interval '1 day')
         AND weight_g > 0
       GROUP BY grade ORDER BY count DESC`,
      [date, days]
    );

    const { rows: stats } = await ocrQuery(
      `SELECT ROUND(AVG(weight_g)::numeric, 1) AS avg_weight_g,
         MIN(weight_g) AS min_weight_g, MAX(weight_g) AS max_weight_g,
         ROUND(STDDEV(weight_g)::numeric, 1) AS stddev_weight_g,
         COUNT(*)::int AS total
       FROM operations_log
       WHERE timestamp >= ($1::date - ($2 || ' days')::interval) AND timestamp <= ($1::date + interval '1 day')
         AND weight_g > 0`,
      [date, days]
    );
    const s = stats[0] || {};

    const distHeaders = ['Grade', 'Count', 'Percentage'];
    const distAlign    = ['center', 'right', 'right'];
    const distRows = dist.map(r => [fmtGrade(r.grade), r.count, `${r.percentage}%`]);

    const statRows = [
      ['Avg Weight', fmtWeight(s.avg_weight_g)],
      ['Min Weight', fmtWeight(s.min_weight_g)],
      ['Max Weight', fmtWeight(s.max_weight_g)],
      ['Std Deviation', fmtWeight(s.stddev_weight_g)],
      ['Total Crates', s.total || 0],
    ];
    const statAlign = ['left', 'right'];

    const hdr = docHeader({ title: 'Grade Quality Export', date, days, generatedBy });

    if (format === 'csv') {
      const csv = buildCsv(distHeaders, distRows)
        + '\n\nSPC Metrics\n' + statRows.map(r => r.join(',')).join('\n');
      return saveAndRespond(res, 'grade-quality', 'csv', `grade-quality-${date}`, csv, null, generatedBy);
    }

    if (format === 'xlsx') {
      const buf = buildXlsx([
        { name: 'Grade Distribution', headers: distHeaders, rows: distRows, align: distAlign },
        { name: 'SPC Metrics', headers: ['Metric', 'Value'], rows: statRows, align: statAlign },
      ]);
      return saveAndRespond(res, 'grade-quality', 'xlsx', `grade-quality-${date}`, null, buf, generatedBy);
    }

    const html = buildHtmlReport(`Grade Quality Export — ${date} (${days}-day window)`, [
      hdr,
      { heading: 'Grade Distribution', table: [distHeaders, ...distRows], align: distAlign },
      { heading: 'Statistical Process Control', table: [['Metric', 'Value'], ...statRows], align: statAlign },
    ]);
    saveAndRespond(res, 'grade-quality', 'html', `grade-quality-${date}`, html, null, generatedBy);
  } catch (err) {
    console.error('[Reports] grade-quality error:', err);
    res.status(500).json({ error: 'Report generation failed' });
  }
});

// ═══════════════════════════════════════════════════════════════════════
// POST /api/reports/downtime
// ═══════════════════════════════════════════════════════════════════════

router.post('/downtime', async (req, res) => {
  try {
    const { date, format = 'html', days = 7 } = req.body;
    const generatedBy = req.user?.email || 'Admin User';

    const { rows: gaps } = await ocrQuery(
      `WITH ordered AS (
         SELECT timestamp,
           LAG(timestamp) OVER (ORDER BY timestamp) AS prev_ts
         FROM operations_log
         WHERE timestamp >= ($1::date - ($2 || ' days')::interval)
           AND timestamp <= ($1::date + interval '1 day')
       )
       SELECT prev_ts::text AS from_time, timestamp::text AS to_time,
         EXTRACT(EPOCH FROM (timestamp - prev_ts))::int AS gap_seconds
       FROM ordered
       WHERE EXTRACT(EPOCH FROM (timestamp - prev_ts)) > 60
       ORDER BY gap_seconds DESC
       LIMIT 50`,
      [date, days]
    );

    const { rows: countRows } = await ocrQuery(
      `SELECT COUNT(*)::int AS total_entries,
         COUNT(DISTINCT DATE(timestamp))::int AS active_days
       FROM operations_log
       WHERE timestamp >= ($1::date - ($2 || ' days')::interval)
         AND timestamp <= ($1::date + interval '1 day')`,
      [date, days]
    );
    const c = countRows[0] || {};

    const totalGapSec = gaps.reduce((s, g) => s + (g.gap_seconds || 0), 0);
    const mtbfMin = gaps.length > 0 ? Math.round(totalGapSec / gaps.length / 60) : null;

    const headers = ['From', 'To', 'Gap (s)', 'Gap (min)'];
    const align   = ['left', 'left', 'right', 'right'];
    const dataRows = gaps.map(g => [fmtTs(g.from_time), fmtTs(g.to_time), g.gap_seconds, Math.round(g.gap_seconds / 60)]);

    const hdr = docHeader({ title: 'Device Downtime Log', date, days, generatedBy });

    if (format === 'csv') {
      const summary = `Active Days,${c.active_days || 0}\nTotal Entries,${c.total_entries || 0}\nMTBF (min),${mtbfMin ?? 'N/A'}\n`;
      const csv = summary + '\n' + buildCsv(headers, dataRows);
      return saveAndRespond(res, 'downtime', 'csv', `downtime-${date}`, csv, null, generatedBy);
    }

    if (format === 'xlsx') {
      const buf = buildXlsx([
        { name: 'Downtime Gaps', headers, rows: dataRows, align },
      ]);
      return saveAndRespond(res, 'downtime', 'xlsx', `downtime-${date}`, null, buf, generatedBy);
    }

    const html = buildHtmlReport(`Device Downtime Log — ${date} (${days}-day window)`, [
      hdr,
      { heading: 'Availability Summary', text: `Active Days: ${c.active_days || 0}  |  Total Entries: ${c.total_entries || 0}  |  MTBF: ${mtbfMin ? `${mtbfMin} min` : 'N/A'}  |  Detected Gaps: ${gaps.length}` },
      { heading: 'Detected Gaps (> 60 s between entries)', table: [headers, ...dataRows], align },
    ]);
    saveAndRespond(res, 'downtime', 'html', `downtime-${date}`, html, null, generatedBy);
  } catch (err) {
    console.error('[Reports] downtime error:', err);
    res.status(500).json({ error: 'Report generation failed' });
  }
});

// ═══════════════════════════════════════════════════════════════════════
// GET /api/reports/download/:id
// ═══════════════════════════════════════════════════════════════════════

router.get('/download/:id', async (req, res) => {
  try {
    const { rows } = await query(
      'SELECT file_path, file_name, format FROM grading.report_exports WHERE id = $1',
      [req.params.id]
    );
    if (rows.length === 0) return res.status(404).json({ error: 'Report not found' });

    const r = rows[0];
    if (!fs.existsSync(r.file_path)) return res.status(404).json({ error: 'File missing from disk' });

    const mime = r.format === 'xlsx' ? 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
      : r.format === 'csv' ? 'text/csv' : 'text/html';
    res.setHeader('Content-Type', mime);
    res.setHeader('Content-Disposition', `attachment; filename="${r.file_name}"`);
    res.sendFile(r.file_path);
  } catch (err) {
    console.error('[Reports] download error:', err);
    res.status(500).json({ error: 'Download failed' });
  }
});

// ═══════════════════════════════════════════════════════════════════════
// GET /api/reports/history
// ═══════════════════════════════════════════════════════════════════════

router.get('/history', async (req, res) => {
  try {
    const { rows } = await query(
      `SELECT id, file_name, report_type, format, generated_by, created_at
       FROM grading.report_exports ORDER BY created_at DESC LIMIT 20`
    );
    res.json({ exports: rows });
  } catch (err) {
    console.error('[Reports] history error:', err);
    res.status(500).json({ error: 'Failed to load history' });
  }
});

export default router;
